version: '3.8'

services:
  db:
    image: postgres:15
    container_name: avicola_postgres
    restart: always
    environment:
      # Usamos las variables del .env para que coincida con tu código NestJS
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-123}
      POSTGRES_DB: ${DB_NAME:-avicola_db}
      TZ: America/Bogota
    ports:
      - "5432:5432" # Mapeo estándar de PostgreSQL
    volumes:
      - postgres_avicola_data:/var/lib/postgresql/data

volumes:
  postgres_avicola_data: