import { MigrationInterface, QueryRunner } from "typeorm";

export class TablasIniciales1773322253999 implements MigrationInterface {
    name = 'TablasIniciales1773322253999'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "usuario_rol" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "usuario_id" integer, CONSTRAINT "PK_6c336b0a51b5c4d22614cb02533" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "usuario_rol" ADD CONSTRAINT "FK_29e9a9079c7ba01c1b301cf5555" FOREIGN KEY ("usuario_id") REFERENCES "usuario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "usuario_rol" DROP CONSTRAINT "FK_29e9a9079c7ba01c1b301cf5555"`);
        await queryRunner.query(`DROP TABLE "usuario_rol"`);
    }

}
